### PR TITLE
Detect offenses within `class_eval/exec` block

### PR DESCRIPTION
**Pull request by viralpraxis**
Resolves https://github.com/rubocop/rubocop-thread_safety/issues/2

BTW @mikegee maybe it's time for a release? There are a lot of unpublished changes atm 🙂

### CODE REVIEW

**Comment by mikegee** [comment]
> maybe it's time for a release? There are a lot of unpublished changes atm 🙂

I agree. Thank you for that. :)

I added you on rubygems.org. Feel free to bump the version and publish a release. 👍

**Comment by viralpraxis** [comment]
> > maybe it's time for a release? There are a lot of unpublished changes atm 🙂
> 
> I agree. Thank you for that. :)
> 
> I added you on rubygems.org. Feel free to bump the version and publish a release. 👍

Thanks! I'll do it a little bit later, gonna take a look at the changes to make sure they're all fine first

**Comment by viralpraxis** [comment]
Regarding this PR, it might be that we need to change the offense message to avoid confusion. This cop now reports class instance variables which are not in a method, so "Avoid instance variables in class methods." is a little bit misleading.

**Comment by mikegee** [comment]
> Regarding this PR, it might be that we need to change the offense message to avoid confusion. This cop now reports class instance variables which are not in a method, so "Avoid instance variables in class methods." is a little bit misleading.

Makes sense 👍 

You could extract a new cop or make the message longer to explain things. 🤷

**Comment by viralpraxis** [comment]
> > Regarding this PR, it might be that we need to change the offense message to avoid confusion. This cop now reports class instance variables which are not in a method, so "Avoid instance variables in class methods." is a little bit misleading.
> 
> Makes sense 👍
> 
> You could extract a new cop or make the message longer to explain things. 🤷

I think the message "Avoid class instance variables" should be good (that's basically what we're trying to say: any class instance variable is potentially unsafe, we mostly track it inside class methods, but that's just an implementation detail/restriction). But it implies we should change cop's name as well. We can do it with rubocop's built-in [config obsoletion mechanism](https://docs.rubocop.org/rubocop/extensions.html#config-obsoletions). @mikegee What do you think about this?

**Comment by mikegee** [comment]
> But it implies we should change cop's name as well (`InstanceVariableInClassMethod` -> `ClassInstanceVariable`). We can do it with rubocop's built-in [config obsoletion mechanism](https://docs.rubocop.org/rubocop/extensions.html#config-obsoletions). @mikegee What do you think about this?

That sounds right to me 👍

**Comment by viralpraxis** [comment]
> > But it implies we should change cop's name as well (`InstanceVariableInClassMethod` -> `ClassInstanceVariable`). We can do it with rubocop's built-in [config obsoletion mechanism](https://docs.rubocop.org/rubocop/extensions.html#config-obsoletions). @mikegee What do you think about this?
> 
> That sounds right to me 👍

Fine 👍🏻, let me do it in separate PR to keep this one simple, is it OK to merge as is?

**Comment by viralpraxis** [comment]
@mikegee I'l cut 0.6.0 today, everything looks fine

**Pull request merged**
