### PR TITLE
Add Ruby 3.3 to CI matrix

### PR DESCRIPTION
**Pull request by m-nakamura145**
This PR adds Ruby 3.3 to CI matrix.

### CODE REVIEW

**Comment by mikegee** [comment]
Thank you for the contribution! ❤️ 

Looks like we need a bit of maintenance on that Lint cop. There's a bunch of warnings too. (I'm a little embarrassed.)

Do you feel like helping on those?

**Comment by m-nakamura145** [comment]
@mikegee Of course! Should I fix the tests where Rubocop warnings were issued in this Pull Request?

**Comment by mikegee** [comment]
I'm glad you are willing to help. Separate or together are both fine with me. Those fixes aren't related to this PR, but you could put them together as "maintenance" in one PR, if you want.

**Comment by m-nakamura145** [comment]
@mikegee Thank you! I will add new commits to this Pull Request. Is it okay to proceed with the approach of fixing the tests that generated warnings, without changing the Rubocop `RSpec/ExampleLength` rules?"

**Comment by mikegee** [comment]
🤔 Looks like `RSpec/ExampleLength` wants our examples 5 for fewer lines. I don't think that's worth rewriting a lot of specs. I think we should set a project setting for that cop to allow 11 or whatever makes it stop complaining. 11 line examples don't seem that bad to me.

But, I'm happy to accept any approach you want.

**Comment by m-nakamura145** [comment]
@mikegee I agree with your opinion. I have added the `RSpec/ExampleLength` setting to `.rubocop.yml`. 
ca8ffb7

**Comment by mikegee** [comment]
Thanks so much!

**Pull request merged**
